    // insertAtTail(tail, 12);
    // insertAtTail(tail, 13);
    // insertAtHead(head, 5);
    // insertAtHead(head, 7);
    // insertAtHead(head, 9);
    // insertAtHead(head, 11);
    // traverse(head);
    // insertAtPosition(head, 9, 100);
    // traverse(head);
    // deleteNode(head, 19);
    // traverse(head);
    // cout << length(head) << endl;